#!/usr/bin/env python

import socket

def redBanner(ip,port):
    try:
        socket.setdefaulttimeout(2)
        s=socket.socket()
        s.connect((ip,port))
        banner=s.recv(1024)
        return banner
    except Exception, e:
        print "[-] Error" + str(e)
def main():
    ip1='5.9.219.38'
    ip2='5.2.9.218'
    port=21
    banner1=redBanner(ip1,port)
    if banner1:
        print "[+]" + ip1 + ":" + banner1
    banner2=redBanner(ip2,port)
    if banner2:
        print "[+]" + ip2 + ":" + banner2
        
if __name__=='__main__':
    main()
